# Generated by Django 4.1.1 on 2022-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'feedback form',
                'verbose_name_plural': 'feedback forms',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
