# Generated by Django 4.1.1 on 2022-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_feedback_name_alter_feedback_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('textarea', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'feedback2 form',
                'verbose_name_plural': 'feedback2 forms',
            },
        ),
    ]
