# Generated by Django 4.1.1 on 2022-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_feedback2_feedback_email_feedback_textarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='textarea',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
